### ISSUE TITLE
Anyway to install this on internal storage of Atomic Pi

### ISSUE THREAD

**Issue by travisboss** [1Jeff1/Atomic-Pi-OpenWrt#3]
Just curious if you or anyone else has been able to install this on the internal storage of the Atomic Pi and if so, how?

**Comment by 1Jeff1** [comment]
I use Ubuntu live USB stick, then dd the OpenWrt image to the internal eMMC storage :
```
sudo dd if= xxx.img of=/dev/mmcblk0 bs=10MB
```
or the Disks app:

![Screenshot from 2020-02-12 17-47-25](https://user-images.githubusercontent.com/46228800/74363988-aada7500-4d99-11ea-8879-ffcf4bb2cee0.jpg)
