### ISSUE TITLE
Request larger root storage?

### ISSUE THREAD

**Issue by travisboss** [1Jeff1/Atomic-Pi-OpenWrt#5]
Hi Jeff,

I was wondering if in your builds you could use more of the eMMC storage?  If not any tips on your build environment?  I tried to build this with your config but did get a failure, I also wanted to add mosh-server to the build hence why I gave it a try.

Appreciate it.

**Comment by potato1992** [comment]
> Hi Jeff,
> 
> I was wondering if in your builds you could use more of the eMMC storage? If not any tips on your build environment? I tried to build this with your config but did get a failure, I also wanted to add mosh-server to the build hence why I gave it a try.
> 
> Appreciate it.

Hello,
I can help you. Here is my ways to install the openwrt with all the spare space:
1. Make a Ubuntu Mate bootable U DIsk, and copy balenaEtcher into it.
2. Install openwrt to the EMMC using balenaEtcher. (sure you can use dd command)
3. Open GParted (ubuntu mate has it), extend the last partition of the EMMC to fully used space.
4. Done

And I am not sure if it is possible to extend the partition after the first boot (in my case I failed).

**Comment by 1Jeff1** [comment]
Hi
I uploaded a build with more storage https://github.com/1Jeff1/Atomic-Pi-OpenWrt/tree/master/atomic-pi-snapshot-r12857

**Comment by travisboss** [comment]
Thanks again Jeff, was going to update but curious if I can keep settings wiht this upgrade or do I need to factory reset?
